### ISSUE TITLE
ArXiv ChatGuru

### ISSUE THREAD

**Issue by Nobelman** [RedisVentures/redis-openai-qna#17]
Объяснит любое исследование доступным языком.

Достаточно отправить заголовок нужной статьи, а нейронка сама извлечет все данные с портала ArXiv, пропустил их через себя и выдаст вам краткую и понятную суть. Если же и этого мало — есть чат, в котором можно задавать любые вопросы по теме.

Математика, физика, Data science и любые другие сложные темы теперь может освоить любой желающий.

**Comment by Spartee** [comment]
Apologies, I'm not sure the translation of this is working well. is there an issue?
