### ISSUE TITLE
docker compose up error!! help

### ISSUE THREAD

**Issue by lilinrestart** [RedisVentures/redis-openai-qna#18]
arxivchatguru-redis-1  | 9:M 23 Oct 2023 05:59:20.357 * <redisgears_2> Failed loading RedisAI API.
arxivchatguru-redis-1  | 9:M 23 Oct 2023 05:59:20.357 * <redisgears_2> RedisGears v2.0.13, sha='c7993a0bb6f8e1a0a4b65cf44136bd7147967769', build_type='releasebuilt_for='Linux-ubuntu22.04.x86_64'.
arxivchatguru-redis-1  |
arxivchatguru-redis-1  | 9:M 23 Oct 2023 05:59:20.360 * <redisgears_2> Registered backend: js.
arxivchatguru-redis-1  | 9:M 23 Oct 2023 05:59:20.360 * Module 'redisgears_2' loaded from /opt/redis-stack/lib/redisgears.so
arxivchatguru-redis-1  | 9:M 23 Oct 2023 05:59:20.360 * Server initialized
arxivchatguru-redis-1  | 9:M 23 Oct 2023 05:59:20.360 * Ready to accept connections tcp
streamlit              | Usage: streamlit run [OPTIONS] TARGET [ARGS]...
streamlit              | Try 'streamlit run --help' for help.
streamlit              |
streamlit              |
streamlit              | Error: Invalid value: File does not exist: App.py
streamlit exited with code 2

**Comment by lilinrestart** [comment]
Will this have an impact？：）
Failed loading RedisAI API.

**Comment by qnqatop** [comment]
hi need to replace with app.py in dockerfile in CMD
 ```
 CMD ["streamlit", "run", "app.py", "--server.fileWatcherType", "none", "--browser.gatherUsageStats", "false","--server.enableXsrfProtection", "false", "--server.address", "0.0.0.0"]
 ```

**Comment by qnqatop** [comment]
> привет, нужно заменить app.py в dockerfile в CMD
> 
> ```
> CMD ["streamlit", "run", "app.py", "--server.fileWatcherType", "none", "--browser.gatherUsageStats", "false","--server.enableXsrfProtection", "false", "--server.address", "0.0.0.0"]
> ```

Also, be sure to look at the ports presented in the README, they write about port 8080 but it is not working, you can look at the current port in the docker-compose file

**Comment by tylerhutcherson** [comment]
This will be addressed by https://github.com/RedisVentures/ArXivChatGuru/pull/20
FYI @Spartee

**Comment by tylerhutcherson** [comment]
Fixed https://github.com/RedisVentures/ArXivChatGuru/pull/20
