### ISSUE TITLE
Need explanation how redis search helps here

### ISSUE THREAD

**Issue by FuncGuy** [RedisVentures/redis-openai-qna#2]
@tylerhutcherson Can you please explain what is happening in brief? or any reference link for understanding in brief so far my understanding is at the app startup it will load csv into redis and when the user queries it will look into redis and construct some tokens[this part is not clear] and it fires request to openAI for the response. How redis search helps here

**Comment by tylerhutcherson** [comment]
Hi! If you checkout the project readme and the app UI when it loads, there's an architecture diagram and explanation.

Redis (via RediSearch) stores document embeddings. When you ask a question,

1. we embed the question with OpenAI.
2. we search redis for relevant document chunks (that help answer the question) using vector similarity search.
3. we pipe the results OpenAI GPT to synthesize an actual answer.
