### ISSUE TITLE
Can vectorstore be superimposed continuously?

### ISSUE THREAD

**Issue by classmatewu** [RedisVentures/redis-openai-qna#8]
Hi, in the current logic, vectorstore either reads existing_index or create_index, whether it can support continuous superposition on the original basis, to achieve the effect of expanding vectorstore
```
def create_vectorstore() -> Redis:
    """Create the Redis vectorstore."""

    embeddings = get_embeddings()

    try:
        vectorstore = Redis.from_existing_index(
            embedding=embeddings,
            index_name=INDEX_NAME,
            redis_url=REDIS_URL
        )
        return vectorstore
    except:
        pass

    # Load Redis with documents
    documents = get_documents()
    vectorstore = Redis.from_documents(
        documents=documents,
        embedding=embeddings,
        index_name=INDEX_NAME,
        redis_url=REDIS_URL
    )
    return vectorstore
```

**Comment by Spartee** [comment]
@classmatewu as in, you'd like the ability to add vectors to an existing index? as in, continually add more each time you spin it up? 

@tylerhutcherson thoughts?

**Comment by classmatewu** [comment]
Yeah, let the store can continue to increase.

**Comment by tylerhutcherson** [comment]
@classmatewu thanks for the feedback.

To clarify, it sounds like the goal is to support a method for updating the existing index with new data so it can grow. There are a couple ways this could be achieved.

Option 1:
Incrementally add documents to an index in "real time" as you add or upload them via the UI?

Option 2:
At each app spin up, add passed in documents to the existing index if it already exists. (Obviously we will want to do this in a way that doesn't duplicate data or work). This is easier to do likely, but also wouldn't allow for incremental updates WHILE the app is already up and running.

**Comment by classmatewu** [comment]
The option 2 is enough, but if there is option 1, it will be even more wonderful.

**Comment by tylerhutcherson** [comment]
Got it. Thanks for the feedback. We have added this to our backlog and will aim to make updates in the coming weeks. In the meantime, we are also supportive of collaboration if you have a PR you'd like to submit.

**Comment by classmatewu** [comment]
okay, thanks a lot. Before that, if I have enough time, I will also submit a PR.

**Comment by Spartee** [comment]
This should all be possible with the currently implementation now. Feel free to re-open if there is another issue :)
